guidebooks/madwizard

package-lock.json
package.json
src/choices/events.ts
src/choices/impl.ts
src/choices/index.ts
src/codeblock/CodeBlockProps.ts
src/codeblock/index.ts
src/graph/Status.ts
src/graph/compile.ts
src/graph/index.ts
src/graph/linearize.ts
src/graph/order.ts
src/graph/progress.ts
src/graph/validate.ts
src/index.ts
src/parser/hack.ts
src/parser/index.ts
src/parser/rehype-code-indexer/index.ts
src/parser/rehype-tabbed/index.ts
src/parser/rehype-tip/index.ts
test/src/index.ts

We need to allow fine-grained imports, and parcel has several bugs that block doing this in the normal way:
https://github.com/parcel-bundler/parcel/issues/7622
https://github.com/parcel-bundler/parcel/issues/5911
This PR also enables validation and progress apis.

chore: major api updates to work around parcel bugs

---

src/graph/validate.ts

fix: graph validator can fail in webpack

---

package-lock.json
package.json
src/index.ts
src/parser/index.ts

This will allow clients to be in charge of fetching the file content.

feat: parser should take a VFileCompatible as input

---

package.json
src/fe/cli.ts
src/graph/index.ts

```shell
npm run tree <uri or filepath>
```
or
```shell
npm run madwizard tree <uri or filepath>
```

feat: cli tree command

---

src/fe/tree/index.ts
src/parser/markdown/remark-import.ts
test/inputs/1/tree.txt
test/inputs/1/wizard.json
test/inputs/10/tree-darwin.txt
test/inputs/10/tree-linux.txt
test/inputs/10/tree-win32.txt
test/inputs/10/wizard-darwin.json
test/inputs/10/wizard-linux.json
test/inputs/10/wizard-win32.json
test/inputs/2/tree.txt
test/inputs/3/tree.txt
test/inputs/3/wizard.json
test/inputs/4/tree.txt
test/inputs/4/wizard.json
test/inputs/5/tree.txt
test/inputs/5/wizard.json
test/inputs/6/tree.txt
test/inputs/6/wizard.json
test/inputs/7/tree.txt
test/inputs/7/wizard.json
test/inputs/8/tree.txt
test/inputs/8/wizard.json
test/inputs/9/tree-darwin.txt
test/inputs/9/tree-linux.txt
test/inputs/9/tree-win32.txt
test/inputs/9/wizard-darwin.json
test/inputs/9/wizard-linux.json
test/inputs/9/wizard-win32.json

Also fixes a missing colon. Should be "Option 1: foo" not "Option 1 foo"

fix: empty titles for imports

---

package-lock.json
package.json
src/fe/cli/index.ts
src/fe/guide/index.ts
src/fe/tree/pretty-print.ts
src/graph/choice-frontier.ts
src/graph/hoistSubTasks.ts
src/graph/linearize.ts
src/graph/validate.ts
src/wizard/index.ts

feat: guide command

---

src/fe/guide/index.ts

Also removes some of the crappy chalk.dim() uses, and updates the use of `wrap()` to feed of `process.stdout.columns`

feat: add title and description to guide

---

src/fe/guide/index.ts

feat: guide should clear console?

---

package-lock.json
package.json
src/parser/markdown/index.ts

These aren't needed if we aren't rendering to html.

chore: madwizard does not need rehype-raw and rehype-slug

---

src/fe/guide/index.ts
src/graph/validate.ts
src/parser/markdown/rehype-code-indexer/index.ts
src/parser/markdown/remark-codeblocks-topmatter.ts

This PR also works around some issues with listr2's handling of errors in concurrent task runs https://github.com/cenk1cenk2/listr2/issues/641

fix: fixes to validator execution

---

src/fe/cli/index.ts
src/fe/guide/index.ts

Also print out a success message in guide

fix: wrap a try/catch around all paths in fe/cli

---

src/fe/guide/index.ts

This PR also fixes some bugs in the per-task done marks.

fix: note when guide run is incomplete

---

src/fe/MadWizardOptions.ts
src/fe/cli/index.ts
src/fe/tree/index.ts
src/fe/tree/pretty-print.ts

feat: tree should not elide content unless given a -n/--narrow option

---

package.json
src/fe/MadWizardOptions.ts
src/fe/cli/index.ts
src/fe/main.ts
src/parser/markdown/index.ts
src/parser/markdown/rehype-tabbed/groups/index.ts
src/parser/markdown/rehype-tabbed/index.ts
test/inputs/10/tree-noopt.txt
test/inputs/10/wizard-noopt.json
test/inputs/9/tree-noopt.txt
test/inputs/9/wizard-noopt.json
test/src/index.ts

e.g. this can help with showing the original task graph before any (or selective) transformations are applied.

feat: add --no-optimize/-O0/--no-aprioris to disable optimizations

---

src/parser/markdown/rehype-tabbed/groups/index.ts
src/parser/markdown/rehype-tabbed/groups/interminal.ts
test/inputs/11/in.md
test/inputs/11/tree-noaprioris.txt
test/inputs/11/tree-noopt.txt
test/inputs/11/tree.txt
test/inputs/11/wizard-noaprioris.json
test/inputs/11/wizard-noopt.json
test/inputs/11/wizard.json

This can help with "text versus html" choices.

feat: detect whether we are running in a terminal

---

src/fe/cli/index.ts
src/fe/guide/index.ts
src/fe/tree/pretty-print.ts

this will print the tree model

feat: add "show plan" option to the guide

---

src/fe/guide/index.ts
src/graph/validate.ts

navigating the listr2 options... persistentOutput, collapse, etc.

fix: improvements for guide task run stdout/stderr piping

---

src/fe/guide/index.ts
src/fe/guide/stream-decorator.ts
src/fe/tree/pretty-print.ts

feat: before executing tasks in guide command, show The Plan

---

src/parser/markdown/snippets/index.ts

our snippetMemo was ignoring error fetches

fix: avoid re-fetching snippet filepaths that previously errored

---

src/choices/groups/expansion.ts

the validators might have a $choice in them

fix: choice expansion should also rewrite validate logic

---

src/choices/groups/expansion.ts

We need to preserve non-expando tabs, so that authors may intermix expansions with static content in a single tab group.

fix: choice expansion removes any non-choice tabs

---

src/choices/groups/expansion.ts

this PR also improves support for choice groups that have multiple expansions

fix: if a choice template fails to expand, don't show the user the template as an option!

---

src/choices/groups/expansion.ts

e.g. so that non-choices can also use ${uuid}

feat: we should do template expansion on all code blocks

---

src/fe/MadWizardOptions.ts
src/fe/cli/index.ts
src/fe/tree/pretty-print.ts
src/graph/compile.ts
src/graph/index.ts
src/graph/linearize.ts
src/graph/provenance.ts
src/graph/vetoes.ts

This PR also adds this as additional output for the "plan" task

feat: add "vetoes" task, to print out all potential veto options

---

src/choices/groups/expansion.ts

This should speed up the `expand` part of the `compile` operation against a `Graph`.

fix: reduce serial bottleneck in template expansion

---

src/fe/cli/index.ts
src/fe/cli/tasks.ts
src/fe/cli/usage.ts

by deferring the load of inquirer, we save loading rxjs, which is only used by the guide command

fix: save about 150-200ms from non-guide cli tasks

---

README.md
src/fe/cli/tasks.ts

This PR also fleshes out the comments in tasks.ts

doc: flesh out tasks and options in README.md

---

src/choices/groups/expansion.ts
src/fe/guide/index.ts
src/graph/compile.ts
src/memoization/index.ts

This is to avoid expensive re-expansion between planning step and execution step.
This PR refactors the statusMemo into src/memoization

feat: memoize expansions

---

src/graph/validate.ts

Versus shelling out to a subprocess. This isn't a huge win, but it saves maybe a few hundred milliseconds.

fix: use `which` npm to expedite validation

---

src/graph/validate.ts

As a madwizard intrinsic.
```python
import sys
import os
import site
sys.exit(0) if os.path.isdir(os.path.join(site.getsitepackages()[0], ${packageName})) else sys.exit(1)
```
|Command|Time|
|----------|-----|
|pip show foo|1100-1600ms|
|python -c 'import foo'|560-650ms|
|madwizard-python-package-installed foo|16ms|

feat: add optimized `madwizard-python-package-installed` validator to check it a python package is installed

---

src/fe/guide/index.ts
src/memoization/index.ts
src/wizard/index.ts

this results in potentially redoing expensive validation after every choice

fix: validation results for choices are not memoized

---

src/graph/validate.ts

this is for `pip install --user foo`

fix: update madwizard-python-package-installed to support USER_SITE

---

src/graph/validate.ts
test/inputs/21/in.md
test/inputs/21/run.txt
test/inputs/21/tree-noaprioris.txt
test/inputs/21/tree-noopt.txt
test/inputs/21/tree.txt
test/inputs/21/wizard-noaprioris.json
test/inputs/21/wizard-noopt.json
test/inputs/21/wizard.json

i.e. when the variable expansion is quoted

fix: export FOO="$BAR" does not work

---

src/codeblock/CodeBlockProps.ts
src/fe/guide/index.ts
src/graph/validate.ts
src/memoization/index.ts
src/parser/markdown/frontmatter/KuiFrontmatter.ts
src/wizard/index.ts
test/inputs/12/wizard-noopt.json
test/inputs/17/wizard-noopt.json
test/inputs/22/wizard-noaprioris.json
test/inputs/22/wizard-noopt.json
test/inputs/22/wizard.json
test/inputs/24/in.md
test/inputs/24/run.txt
test/inputs/24/tree-noaprioris.txt
test/inputs/24/tree-noopt.txt
test/inputs/24/tree.txt
test/inputs/24/wizard-noaprioris.json
test/inputs/24/wizard-noopt.json
test/inputs/24/wizard.json

See test/inputs/24/in.md for an example

feat: custom executables in code block topmatter

---

src/fe/guide/index.ts

This happens when we have iterations of the guide that ask no questions, rather only execute tasks.
This PR also uses inverse colors for the "Choice x" text.

fix: "Choice x" sometimes skips from e.g. Choice 1 to Choice 3

---

src/exec/ray-submit.ts

fix: ray-submit uses improperly formatted json

---

src/fe/cli/madwizardRead.ts
src/parser/markdown/fetch.ts
src/parser/markdown/index.ts

fix: in some clients, vfile seems to use `/` as cwd

---

.github/workflows/test.yml
bin/madwizard.js
package-lock.json
package.json
src/choices/groups/index.ts
src/fe/cli/index.ts
src/fe/index.ts
src/parser/index.ts
src/parser/markdown/rehype-tabbed/index.ts
src/version.ts
test/src/index.ts
tsconfig.json

We don't need it, and it's horribly buggy.
BREAKING CHANGE: now we can do the right thing with our exports, but this means you will now need to import the component, CLI, Graph, Parser, ...

chore: ditch parcel

---

src/fe/cli/madwizardRead.ts

1) we look locally first, even for given filepaths that lack a `.md` extension
2) we then look sequentially, first for `foo + ".md"` then for `foo + "/index.md"`
2a) the common case is probably the latter, not the former
2b) we can try both in parallel, via `Promise.any()`
As a result, the number of file lookups should go from 3 to 1, at least from a latency perspective, for the common case.

fix: optimize loading from store

---

src/choices/groups/aprioris/gpu.ts
src/choices/groups/aprioris/index.ts

for now, this depends on an environment variable being set `NUM_GPUs`

feat: add apriori detection for gpu availability

---

bin/regen.sh
src/exec/export.ts
src/exec/ray-submit.ts
test/inputs/21/in.md
test/inputs/21/run.txt
test/inputs/21/tree-noaprioris.txt
test/inputs/21/tree-noopt.txt
test/inputs/21/tree.txt
test/inputs/21/wizard-noaprioris.json
test/inputs/21/wizard-noopt.json
test/inputs/21/wizard.json

fix: improve support for exports with default value

---

src/choices/groups/expansion.ts
src/graph/choice-frontier.ts
src/graph/compile.ts

This is an optimization, not a functional change in the graph models. Hence no tests should be affected.

fix: choice expansion should not expand beyond first choice

---

src/choices/groups/expansion.ts

=== "expand(echo 3, Echoing 3)"

feat: add support for guidebooks to pretty print an expansion message

---

src/exec/export.ts
src/parser/markdown/snippets/index.ts
test/inputs/31/run.txt
test/inputs/31/tree-noaprioris.txt
test/inputs/31/tree-noopt.txt
test/inputs/31/tree.txt
test/inputs/31/wizard-noaprioris.json
test/inputs/31/wizard-noopt.json
test/inputs/31/wizard.json

we set the env var, but never unset it
this PR includes support for `unset FOO`

fix: import env vars are not scoped to the import

---

src/exec/ray-submit.ts

If we have a LOGDIR_STAGE from the guidebooks...
```javascript
{ jobid, cmdline, runtimeEnv, language, source }
```

feat: ray-submit shoudl write out a job.json description

---

src/choices/groups/expansion.ts
src/exec/export.ts

we may issue multiple expansion queries

fix: expansion memo has a race condition

---

src/graph/collapseValidated.ts

Remove unused computation of choiceFrontier

fix: small cleanup to collapseValidated code

---

src/fe/guide/index.ts

only if MWCLEAR is set will we now clear the screen between choices

fix: in guide, don't clear screen by default

---

package-lock.json
package.json
src/choices/impl.ts
src/choices/index.ts
src/fe/cli/index.ts
src/fe/cli/tasks.ts
src/fe/profiles/index.ts
src/fe/profiles/table.ts
src/fe/tree/pretty-print.ts
src/index.ts
src/memoization/index.ts
src/parser/markdown/index.ts
src/profiles/clone.ts
src/profiles/delete.ts
src/profiles/index.ts
src/profiles/list.ts
src/profiles/persist.ts
src/profiles/restore.ts
src/util/cache.ts

- new `listProfiles` API call
- the `ChoiceState` now wraps around a `Profile`, which has a name, creation timestamp, etc.
For now, we will attempt to schema-align older persisted profiles to the new form, when deserializing them.

feat: new api and improved handling around profiles

---

src/exec/ray-submit.ts
src/profiles/delete.ts
src/profiles/index.ts
src/profiles/list.ts
src/profiles/paths.ts
src/profiles/persist.ts
src/profiles/restore.ts
src/util/cache.ts

Some refactoring to facilitate this.

chore: export `Profiles.profilesPath()`

---

src/profiles/index.ts

This is a convenience wrapper around `Profiles.list()` plus a sort.

feat: add convenience `Profiles.lastUsed()` API

---

src/exec/ray-submit.ts

Currently, this assumes the following directory structure for the provided working-dir:
- main.py
- requirements.txt (optional)
- runtime-env.yaml (optional)
TODO: allow for a config-yaml that specifies the name of the main.py?

feat: update ray-submit intrinsic with initial support for application templates

---

src/exec/ray-submit.ts
src/fe/cli/index.ts
src/fe/cli/tasks.ts
src/fe/cli/usage.ts
src/fe/profiles/index.ts

The command line dash-dash args will be availble to guidebooks via the `${GUIDEBOOK_DASHDASH}` environment variable.

feat: support for passing through CLI -- <rest> args to guidebooks

---

src/exec/ray-submit.ts
src/fe/cli/index.ts

This PR also improves support for ~ home dir shorthand.

fix: improve support for empty dash dash options

---

src/fe/cli/index.ts

Regression from switch to yargs-parser

fix: --no-profile option does not work

---

src/fe/tree/ui.ts

plus underline, strikethrough, italics markdown.

feat: improve rendering of bold text in ANSI terminals

---

src/fe/cli/index.ts

chore: update non-yargs manual parsing of --assert CLI options

---

src/fe/MadWizardOptions.ts
src/fe/cli/index.ts

Previously, this was only possible via CLI options, which is hard w.r.t. shell escaping

feat: allow assertions to be passed programmatically

---

src/exec/ray-submit.ts

Also entrypoints quoted, like `--entrypoint="bash -c foo.sh"`

fix: ray-submit intrinsic mishandles non-python entrypoints

---

src/exec/export.ts
src/fe/guide/index.ts

Reverts guidebooks/madwizard#433

Revert "fix: more fixes for status memo invalidation"

---

package.json

Reverts guidebooks/madwizard#432

Revert "fix: restore accidentally removed prepack script"

---

src/fe/cli/defaults.ts
src/profiles/defaultName.ts
src/profiles/index.ts

This PR also consolidates a few places where we had the default profile name hard-coded.

feat: `Profiles.createIfNeeded()` creates an empty profile if none exists

---

packages/madwizard/src/fe/guide/index.ts

before this, we would clear the screen in a way that would hide the initial title.

fix: improve logic for initial clear screen

---

packages/madwizard/src/fe/cli/commands/advanced.ts
packages/madwizard/src/fe/cli/commands/guide/index.ts
packages/madwizard/src/fe/cli/commands/guide/options.ts
packages/madwizard/src/fe/cli/commands/json/index.ts
packages/madwizard/src/fe/cli/commands/mirror.ts
packages/madwizard/src/fe/cli/commands/plan/index.ts
packages/madwizard/src/fe/cli/commands/profile.ts
packages/madwizard/src/fe/cli/index.ts
packages/madwizard/src/fe/cli/options.ts

This also removes the `build` command.

fix: more cleanup of options, descriptions and underlying code

---

packages/madwizard/src/fe/cli/commands/guide/index.ts
packages/madwizard/src/fe/cli/index.ts

fix: improve return type of `cli` export

---

package-lock.json
packages/madwizard/package.json
packages/madwizard/src/fe/tree/ui.ts

it is relatively expensive to load (100-130ms), and used very rarely in practice (so far, at least).

feat: remove fancy code highlighting from AnsiUI

---

packages/madwizard/bin/regen.sh
packages/madwizard/src/choices/groups/expansion.ts
packages/madwizard/src/graph/index.ts
packages/madwizard/src/graph/linearize.ts
packages/madwizard/test/inputs/43/in.md
packages/madwizard/test/inputs/43/run-noaprioris.txt
packages/madwizard/test/inputs/43/run-noopt.txt
packages/madwizard/test/inputs/43/run.txt
packages/madwizard/test/inputs/43/tree-noaprioris.txt
packages/madwizard/test/inputs/43/tree-noopt.txt
packages/madwizard/test/inputs/43/tree.txt
packages/madwizard/test/inputs/43/wizard-noaprioris.json
packages/madwizard/test/inputs/43/wizard-noopt.json
packages/madwizard/test/inputs/43/wizard.json
packages/madwizard/test/inputs/44/in.md
packages/madwizard/test/inputs/44/nested.md
packages/madwizard/test/inputs/44/run-noaprioris.txt
packages/madwizard/test/inputs/44/run-noopt.txt
packages/madwizard/test/inputs/44/run.txt
packages/madwizard/test/inputs/44/tree-noaprioris.txt
packages/madwizard/test/inputs/44/tree-noopt.txt
packages/madwizard/test/inputs/44/tree.txt
packages/madwizard/test/inputs/44/wizard-noaprioris.json
packages/madwizard/test/inputs/44/wizard-noopt.json
packages/madwizard/test/inputs/44/wizard.json

see packages/madwizard/test/inputs/43 and packages/madwizard/test/inputs/44 for examples

fix:  is not expanded for non-forms

---

packages/madwizard/src/choices/groups/expansion.ts
packages/madwizard/src/graph/workaroundMultipleChoicesPerFile.ts
packages/madwizard/test/inputs/23/wizard-noaprioris.json
packages/madwizard/test/inputs/23/wizard-noopt.json
packages/madwizard/test/inputs/3/wizard-noopt.json
packages/madwizard/test/inputs/5/wizard-noaprioris.json
packages/madwizard/test/inputs/5/wizard-noopt.json
packages/madwizard/test/inputs/5/wizard.json
packages/madwizard/test/inputs/6/wizard-noopt.json
packages/madwizard/test/inputs/7/wizard-noopt.json
packages/madwizard/test/inputs/8/wizard-noopt.json

This solidifies the hack in the original PR #581

fix: improved fix for multiple choices in a single file

---

package-lock.json
packages/madwizard/package.json
packages/madwizard/src/fe/MadWizardOptions.ts
packages/madwizard/src/fe/cli/commands/profile.ts
packages/madwizard/src/fe/cli/defaults.ts
packages/madwizard/src/fe/cli/index.ts
packages/madwizard/src/fe/cli/options.ts
packages/madwizard/src/fe/profiles/details.ts
packages/madwizard/src/profiles/get.ts

Also adds an `appName` attribute to MadWizardOptions to allow clients to customize the output (instead of being hard-coded to an appName of "madwizard")

feat: add `madwizard profile get` command

---

packages/madwizard/src/exec/shell.ts

Reverts guidebooks/madwizard#660

Revert "fix: pass through GUIDEBOOK_DASHDASH again"

---

packages/madwizard/src/choices/groups/expansion.ts
packages/madwizard/test/inputs/50/multi.md
packages/madwizard/test/inputs/50/run-noaprioris.txt
packages/madwizard/test/inputs/50/run.txt
packages/madwizard/test/inputs/50/tree-noaprioris.txt
packages/madwizard/test/inputs/50/tree-noopt.txt
packages/madwizard/test/inputs/50/tree.txt
packages/madwizard/test/inputs/50/wizard-noaprioris.json
packages/madwizard/test/inputs/50/wizard-noopt.json
packages/madwizard/test/inputs/50/wizard.json
packages/madwizard/test/inputs/51/form.md
packages/madwizard/test/inputs/51/run-noaprioris.txt
packages/madwizard/test/inputs/51/run.txt
packages/madwizard/test/inputs/51/tree-noaprioris.txt
packages/madwizard/test/inputs/51/tree-noopt.txt
packages/madwizard/test/inputs/51/tree.txt
packages/madwizard/test/inputs/51/wizard-noaprioris.json
packages/madwizard/test/inputs/51/wizard-noopt.json
packages/madwizard/test/inputs/51/wizard.json

feat: for dynamic form expansions, support $idx expansion, to represent index in form

---

packages/madwizard/src/fe/guide/index.ts

Allow select screens to accept keyboard input to filter list of options (useful for long lists).

feat: change select prompt to use AutoComplete
