guidebooks/madwizard

- src/graph/compile.ts
In case we cannot infer a title and description, allow clients to pass through a priori information, e.g. from the file they fetched.
> feat: update graph compile() to allow passing through a title and description

- src/parser/markdown/rehype-wizard.ts
I don't know why tsc didn't catch this.
> fix: rehype-wizard has a use before declaration

- src/fe/cli/index.ts
- src/fe/guide/index.ts
- src/fe/main.ts
- src/graph/choice-frontier.ts
- src/graph/hoistSubTasks.ts
- src/graph/optimize.ts
- src/wizard/index.ts
Let's just simplify this and assume for now that `collapseMadeChoices` transformer is applied to the graph. This will let us consolidate all of the choice state checking into that one transformer.
> chore: remove lots of unnecessary uses of choice state

- src/parser/markdown/rehype-wizard.ts
rehype-wizard is missing a SKIP in the visitor when reachign a nested import.
> fix: nested wizards result in bogus tree

- tsconfig.json
We have coverage for this in our eslint rules, and it makes debugging annoying (e.g. comment out a line to try something out, and your code no longer compiles)
> chore: disable `noUnusedLocals` in tsconfig

- src/codeblock/CodeBlockProps.ts
- src/fe/cli/index.ts
- src/graph/index.ts
- src/parser/markdown/rehype-code-indexer/index.ts
- src/parser/markdown/util/toMarkdownString.ts
- src/wizard/index.ts
- test/inputs/1/wizard.json
- test/inputs/10/wizard-darwin.json
- test/inputs/10/wizard-linux.json
- test/inputs/10/wizard-win32.json
- test/inputs/3/wizard.json
- test/inputs/4/wizard.json
- test/inputs/5/wizard.json
- test/inputs/6/wizard.json
- test/inputs/7/wizard.json
- test/inputs/8/wizard.json
- test/inputs/9/wizard-darwin.json
- test/inputs/9/wizard-linux.json
- test/inputs/9/wizard-win32.json
- test/src/index.ts
These are very expensive, and not needed for most guide use case?
> fix: delay expensive calls to toMarkdownString

- src/fe/tree/index.ts
- src/fe/tree/ui.ts
They are currently completely excluded from the tree model. This should be a UI decision, of if and how to display optional code blocks.
> feat: tree model should include optional blocks

- src/codeblock/CodeBlockProps.ts
- src/fe/cli/index.ts
- src/parser/markdown/rehype-code-indexer/index.ts
- src/parser/markdown/rehype-tip/index.ts
- src/parser/markdown/rehype-wizard.ts
- src/parser/markdown/util/isElement.ts
- test/inputs/1/wizard.json
- test/inputs/10/wizard-darwin.json
- test/inputs/10/wizard-linux.json
- test/inputs/10/wizard-win32.json
- test/inputs/3/wizard.json
- test/inputs/4/wizard.json
- test/inputs/5/wizard.json
- test/inputs/6/wizard.json
- test/inputs/7/wizard.json
- test/inputs/8/wizard.json
- test/inputs/9/wizard-darwin.json
- test/inputs/9/wizard-linux.json
- test/inputs/9/wizard-win32.json
- test/src/index.ts
We have been somewhat assuming that structure comes from our home-grown Wizards. We should probably switch over to feeding off the heading structure. This PR starts us in that direction.
> fix: improve handling of markdown content that does not use wizards

- src/parser/markdown/rehype-tabbed/groups/homebrew.ts
some source material nicknames the homebrew option "Brew"
> feat: extend homebrew detector to tolerate "Brew"

- src/fe/MadWizardOptions.ts
- src/fe/cli/index.ts
- src/fe/tree/xform.ts
- src/graph/hoistSubTasks.ts
- src/graph/index.ts
- src/parser/index.ts
- src/parser/markdown/index.ts
- src/parser/markdown/rehype-code-indexer/index.ts
- src/parser/markdown/snippets/index.ts
- test/inputs/8/tree.txt
This will allow us a bit more flexibility in consuming mkdocs content. In general, we will need to snarf up the base path from the mkdocs.yml config, because all of the content will be written w.r.t. that base.
This PR also fixes a few issues with the graph and tree formation for "fake" subtasks, i.e. not from imports, but just a way to name a subtask.
> feat: support for --mkdocs flag

- src/fe/cli/index.ts
- src/graph/collapseMadeChoices.ts
- test/src/index.ts
We may collapse away a meaningful title, e.g. if the resulting (collapsed) subgraph is just a code block, and the title was coming from the choice...
> fix: when collapsing choices, make sure to preserve titles

- src/fe/guide/index.ts
Let's treat this as an aside, and loop back to the main question (how do you want to execute the tasks?)
> fix: "show the plan" option in guide shouldn't exit

- src/parser/markdown/remark-codeblocks-topmatter.ts
We were replacing these with `\.`. Let's just treat them like regexps without special interpretation on our part!
> fix: don't be clever about dots in codeblocks.match topmatter

- src/parser/markdown/frontmatter/index.ts
- src/parser/markdown/rehype-code-indexer/index.ts
- src/parser/markdown/util/isElement.ts
- test/inputs/1/wizard.json
- test/inputs/3/wizard.json
- test/inputs/4/wizard.json
- test/inputs/5/wizard.json
- test/inputs/6/wizard.json
- test/inputs/7/wizard.json
- test/inputs/8/wizard.json
When we are scanning for a "first paragraph", we have been ignoring text nodes; we were only looking for paragraph nodes. Text nodes come from cases where there is no newline after a tab title or section header line, for example.
> fix: choices in guide command may be missing description

- src/fe/tree/pretty-print.ts
the `elide()` call in `pretty-print.ts` ignores the width of the optional `indent` parameter
> fix: tree may wrap undesirably

- src/parser/markdown/index.ts
- src/parser/markdown/snippets/index.ts
- src/parser/markdown/snippets/urls.ts
it is often convenient to copy and paste a "normal" github url, rather than having to click a few more times to get the "raw" github url. we can easily do the transformation for the user.
> feat: allow fetching from non-raw github urls

- src/fe/guide/stream-decorator.ts
ugh, this was due to an unprotected `str.repeat(-1)`.
> fix: execs of long command lines may fail with "RangeError: Invalid count value"

- package-lock.json
- package.json
> npm WARN deprecated @types/figures@3.0.1: This is a stub types definition. figures provides its own type definitions, so you do not need this installed.
> chore: remove unnecessary `@types/figures` dependence

- bin/madwizard.js
Since we are using an experimental option, we should probably suppress the inevitable `ExperimentalWarning`.
> fix: add --no-warnings to bin/madwizard.js

- src/fe/cli/index.ts
- src/parser/markdown/rehype-tabbed/groups/arch.ts
- src/parser/markdown/rehype-tabbed/groups/debug.ts
- src/parser/markdown/rehype-tabbed/groups/homebrew.ts
- src/parser/markdown/rehype-tabbed/groups/interminal.ts
- src/parser/markdown/rehype-tabbed/groups/platform.ts
```shell
madwizard aprioris <filepath or uri>
madwizard/aprioris/arch using choice x64 +0ms
madwizard/aprioris/platform using choice darwin +0ms
madwizard/aprioris/homebrew using choice Homebrew +0ms
madwizard/aprioris/interminal using choice Text +0ms
madwizard/aprioris/platform found matching tab group +0ms
madwizard/aprioris/homebrew found matching tab group +0ms
madwizard/aprioris/arch found matching tab group +0ms
madwizard/aprioris/homebrew found matching tab group +0ms
madwizard/aprioris/homebrew found matching tab group +0ms
```
> chore: improved debugging of aprioris detection

- bin/madwizard.js
Apparently macOS didn't need this, but linux does.
> fix: add -S option to /usr/bin/env in bin/madwizard.js

- src/fe/cli/index.ts
- src/fe/guide/index.ts
- src/fe/guide/taskrunner.ts
- src/graph/validate.ts
- src/wizard/index.ts
There's no sense in presenting wizard steps that are already done. We were already doing this for task execution, but not for choices. This PR adds that feature.
We will need to find a way to distinguish between choices that are ok not to repeat and choices that bear repeating. This PR assumes all valid choices do not need to be presented again.
> feat: pre-validate wizard choice steps

- src/fe/guide/index.ts
- src/graph/index.ts
- src/wizard/index.ts
We don't need to start up a spinner, just to immediately detect that we aren't going to re-validate.
> fix: avoid starting up ora spinners when revalidating, if not needed

- src/parser/index.ts
- src/parser/markdown/index.ts
e.g. ibm/cloud/target will fetch from
https://github.com/guidebooks/store/blob/main/guidebooks/ibm/cloud/target.md
> feat: allow fetching from the store in short form

- package-lock.json
- package.json
- src/fe/guide/index.ts
Dunno why, but very odd line wrapping results when terminal-link is involved. This doesn't seem to be an issue with wrap-ansi, as the same text wraps fine without inquirer in the middle.
> fix: avoid use of wrap-ansi in inquirer prompts

- src/fe/guide/index.ts
wraps don't work, but indentation seems to on its own
> fix: restore indentation in descriptions in guide

- src/codeblock/CodeBlockProps.ts
- src/graph/compile.ts
- src/graph/index.ts
- src/graph/validate.ts
- src/parser/markdown/frontmatter/KuiFrontmatter.ts
- src/parser/markdown/rehype-code-indexer/index.ts
- src/parser/markdown/remark-import.ts
- src/parser/markdown/snippets/index.ts
if topmatter of an import has certain unsafe characters, remark-directive fails to process our container directive imports as such. switching from encodeURIComponent to "quoted base64" seems to fix that
this pr also adds initial support for placing import-wide validation in topmatter. not 100% functional yet.
> fix: nested imports may fail due to use of encodeURIComponent

- src/parser/markdown/remark-import.ts
- test/inputs/1/wizard.json
- test/inputs/3/tree-noopt.txt
- test/inputs/3/tree.txt
- test/inputs/3/wizard.json
- test/inputs/4/tree-noopt.txt
- test/inputs/4/tree.txt
- test/inputs/4/wizard.json
- test/inputs/5/tree-noopt.txt
- test/inputs/5/tree.txt
- test/inputs/5/wizard.json
- test/inputs/6/tree-noopt.txt
- test/inputs/6/tree.txt
- test/inputs/6/wizard.json
- test/inputs/7/tree-noopt.txt
- test/inputs/7/tree.txt
- test/inputs/7/wizard.json
- test/inputs/8/wizard.json
we were only looking at the first child of imports, which, due to us! in snippets/, is bound to be a comment
> fix: improve title discovery for imports

- src/graph/validate.ts
both in the export and in the exec!
> fix: export env var support does not properly inherit from process.env

- src/fe/guide/index.ts
we are memoizing "blank" as the status of code blocks, and treating that as a sign that we've already executed
> fix: guide memoizes too aggressively

- bin/madwizard.js
- src/graph/collapseMadeChoices.ts
- src/util/ora-delayed-promise.ts
our ora-promise-with-delay wrapper isn't properly handling underlying exceptions
this can be caused by group expansion failures. there is also a chained issue, when expansion fails, that collapseMadeChoices may have a null pointer exception
> fix: when expansion fails, uncaught exceptions ensue

- bin/terser.sh
- package.json
I don't really get parcel. It seems so buggy. Yet another bug is that it doesn't seem to optimize our builds, despite the docs claiming this is the default for "production" builds (i.e. those outputs of `terser build`.
And if I try to use a `targets`... I can get optimized builds (by explicitly specifying `optimize: true` in the target), but then i don't get a type declaration... sigh.
So this PR uses terser explicitly in our `build` script target.
> chore: use terser to optimize builds

- src/graph/validate.ts
We were only handling foo/ not foo.py i.e. modules that are a single file.
> fix: update madwizard-python-package-installed to support modules foo.py

- src/exec/options.ts
- src/exec/pip-show.ts
- src/exec/ray-submit.ts
- src/graph/validate.ts
- src/memoization/index.ts
This PR only collects pip dependencies surfaced via `pip-show` validation. In the future, I think we can bridge this into the `pip install` code blocks by automatically inferring a validator from the code block?
and TODO: requirements.txt?
> feat: collect pip depenendencies for ray-submit

- .gitignore
- bin/madwizard.js
- package-lock.json
- package.json
- src/fe/MadWizardOptions.ts
- src/fe/cli/index.ts
- src/fe/cli/tasks.ts
- src/parser/markdown/fetch.ts
- src/parser/markdown/index.ts
- src/parser/markdown/snippets/index.ts
- src/parser/markdown/snippets/inliner.ts
- src/parser/markdown/snippets/mirror.ts
build and mirror: these allow for static/ahead-of-time fetching
and inlining of content. This can be helpful to allow shipping
"frozen" forms of content with a build, and capturing remote
content at the same time. By inlining the content ("build", and
mirror calls build over a directory tree), you can also amortize
the cost of many file reads/remote fetches per run.
this PR adds the `--store=xxx` option to the CLI, and the matching `store` option to `MadWizardOptions`. it updates the `mw` front-end to default to using the prebuilt store, but this can be overridden by running `mw` with `MWSTORE=/some/other/path`,
and if you set `MWSTORE=git` it will use https://github.com/guidebooks/store
> feat: add "build" and "mirror" commands to allow for static/ahead-of-time inlining and fetching

- package-lock.json
- package.json
sigh, env-paths 3.0.0 uses `import x from 'node:os'` which webpack isn't happy with (yet)
https://github.com/webpack/webpack/issues/14166
> chore: downgrade env-paths 3.0.0 -> 2.2.1

- src/choices/groups/index.ts
if client does not pass a MadwizardOptions to rehype-tabbed
> fix: aprioris logic can throw null pointer exception

- src/choices/groups/expansion.ts
- src/exec/Executor.ts
- src/exec/custom.ts
- src/exec/index.ts
- src/exec/python.ts
- src/fe/cli/index.ts
- src/fe/cli/madwizardRead.ts
- src/graph/compile.ts
- src/graph/validate.ts
- src/parser/index.ts
- src/parser/markdown/index.ts
- src/parser/markdown/snippets/inliner.ts
This helps with browser integration.
This PR also enables clients to pass in an executor, e.g. for group expansion.
> fix: refactor to push more cli-specific imports into the dynamic cli path

- src/parser/markdown/rehype-code-indexer/index.ts
this helps clients that require `rehype-raw`, which stringifies all properties :(
> feat: allow clients to request that codeblock metadata is base64-encoded in the AST

- src/parser/markdown/rehype-code-indexer/index.ts
oof, we are serializing way too much. we can exclude source and nesting attributes, or... rather, we need to, to avoid gigantic serialized blobs. e.g. 350MB versus 128 bytes
> fix: clients that request base64 code blocks may OOM

- src/index.ts
as
```typescript
import { reader } from 'madwizard'
const data = await (await reader())(filepath)
```
> feat: export madwizardRead

- src/fe/cli/madwizardRead.ts
We already did this for store references, e.g. ml/ray/run.
This PR extends the /index.md implicit suffix for local filepaths.
It also fixes potential problems with cwd in use of `new VFile({ path})` constructs.
> feat: broaden support for implicit index.md in guidebook reader

- bin/madwizard.js
the shim binaries it creates use "-S" as the name of the binary :(
> fix: avoid use of env -S which seems to confuse npm on windows

- src/exec/export.ts
- src/exec/index.ts
- src/fe/MadWizardOptions.ts
- src/fe/cli/index.ts
- src/fe/guide/index.ts
- src/fe/guide/taskrunner.ts
- test/src/index.ts
With this PR, the task runner won't emit anything for `export FOO=bar` and `echo xxx`, unless you specify `--verbose` or `-V` on the command line.
> feat: when running tasks, be a bit quieter

- src/parser/markdown/hack.ts
i don't think we need these for guidebooks. these are more of a UI rendering thing.
In any case, we can't blindly apply remark-marks as it does now. It is completely context insensitive. As a result, it can turn `==` in e.g. python code blocks into `<mark/>`
> fix: avoid remark-marks and remark-keys

- src/choices/groups/expansion.ts
if the expansion results in nothing, we already aren't memoizing the result, but we *are* updating the graph model, oops
> fix: group expansion too aggressively memoizes

- src/graph/collapseValidated.ts
- test/inputs/3/tree-noaprioris.txt
- test/inputs/3/tree.txt
- test/inputs/3/wizard-noaprioris.json
- test/inputs/3/wizard.json
There's no sense in issuing potentially expensive validation tasks after the first choice. 1) may be wasted work; 2) may not even be meaningful, as the choice may alter state in a way that affects the way those contingent validation tasks behave
> fix: graph optimizer should not prematurely validate beyond the first choice

- src/graph/collapseValidated.ts
At some point, I think we may need to redo this in a better way... using choice frontier?
> fix: another refinement to collapse validated up to first choice

- bin/regen.sh
- src/codeblock/CodeBlockProps.ts
- src/exec/index.ts
- src/exec/options.ts
- src/exec/shell.ts
- src/fe/cli/index.ts
- src/fe/guide/index.ts
- src/memoization/index.ts
- src/parser/markdown/rehype-code-indexer/index.ts
- test/inputs/30/in.md
- test/inputs/30/run.txt
- test/inputs/30/tree-noaprioris.txt
- test/inputs/30/tree-noopt.txt
- test/inputs/30/tree.txt
- test/inputs/30/wizard-noaprioris.json
- test/inputs/30/wizard-noopt.json
- test/inputs/30/wizard.json
This PR adds support for asynchronous code block execution, via:
```shell.async
do something
```
An async code block will execute under fire-and-forget semantics, except that the subprocesses will be killed at exit of the main guidebook execution.
> feat: asynchronous code block execution

- src/fe/cli/index.ts
this avoids dangling processes from e.g. bash pipes
> fix: on cleanup, kill process group of spawned subprocesses

- src/graph/collapseValidated.ts
we can't do this, because the user hasn't made that choice that!
apparently we were doing this because of some bugs in the ibm/cloud/login and ibm/cloud/target guidebooks, which resulted in them always asking the user to login or target, respectively
> fix: don't validate inside of choices

- src/fe/cli/index.ts
we don't want a process group kill failure to spoil killing other subprocesses. or, worse, to hang the onExit handler.
> fix: process group kill may fail

- src/fe/cli/index.ts
- src/memoization/index.ts
This PR introduces a `Memoizer.cleanup()` API that those clients may now call.
> fix: clients that call cli API do not benefit from subprocess cleanup

- src/exec/shell.ts
- src/memoization/index.ts
This PR uses a `detached: true` subprocess execution for `shell.async` code blocks. Then, on cleanup, we kill that process group. This seems to fix stragglers (i.e. subprocesses sticking around after exit) for cases where a subprocess spawns subprocesses... At least macos gets confused in this case, and attaches those grandchildren to `1`.
Whereas, by detaching, we ask the OS to create a new process group, one that we can control and kill.
> fix: improvements for cleaning up straggler async processes on exit

- src/exec/export.ts
- src/exec/options.ts
- src/exec/shell.ts
the error message is stored in the env var
> fix: export exec handler does not properly deal with errors

- src/memoization/index.ts
there are bash expressions that use env vars that we don't currently match. e.g. `printenv FOO`
> fix: memo invalidator needs to be more conservative

- src/test/index.ts
e.g.
```shell
npm test 21 22
```
will run just those two inputs
> test: allow specifying which test inputs to run

- src/graph/hoistSubTasks.ts
- test/inputs/8/tree-noaprioris.txt
- test/inputs/8/tree.txt
This PR does not fully fix this problem, but at least gives an ordering that makes more sense. The deeper problem is here:
```typescript
const mySubTasks = removeDuplicates(union(myDominatedSubTasks, frontierAllChoicesSubTasks))
```
this PR gives that swapped order (my, frontier); before it was (frontier, my). The real answer is to find a way to interleave my and frontier subtasks in a way that preserves that initial order of occurence.
> fix: hoistSubTasks optimizer is not order preserving

- src/choices/groups/expansion.ts
- src/choices/impl.ts
- src/choices/index.ts
- src/exec/conda-install.ts
- src/exec/custom.ts
- src/exec/export.ts
- src/exec/index.ts
- src/exec/options.ts
- src/exec/pip-install.ts
- src/exec/pip-show.ts
- src/exec/python.ts
- src/exec/ray-submit.ts
- src/exec/shell.ts
- src/fe/MadWizardOptions.ts
- src/fe/cli/index.ts
- src/fe/cli/madwizardRead.ts
- src/fe/guide/index.ts
- src/fe/guide/taskrunner.ts
- src/fe/tree/pretty-print.ts
- src/graph/collapseValidated.ts
- src/graph/compile.ts
- src/graph/optimize.ts
- src/graph/validate.ts
- src/graph/vetoes.ts
- src/memoization/index.ts
- src/test/index.ts
- src/util/cache.ts
By default now, choices will be stored in a fixed profile (TODO: allow named profiles).
- `--no-profile` CLI option disables profiles altogether
- `--profiles-path` CLI option lets you point to a profiles directory
- `process.env.MWPROFILES_PATH` ibid but via env var
The default profiles path is the platform data directory; e.g. on macOS ~/Library/Application Support/
This PR also does some internal cleanup to avoid Object.assigning Memos and random other stuff. This is helpful, because the default impl `Memoizer` is a class, and so it is important not to mess with `this`. This helps this PR, because we want to pass through extra options, and finally broke things with the way we were smashing memos and options together.
This PR also updates the test rig finally to avoid spawning madwizard …
> feat: initial support for remembered choices

- src/fe/guide/index.ts
we are using enquirer's hint, which places it at the end of the message. but we use newlines in the message, so the hint shows up... oddly.
also, our logic to place a newline between multi-line options is foiled by the sorting we are forced to do, to float the "you selected this last time" option to the top.
> fix: "you selected this last time" text shows up in an odd place

- src/fe/MadWizardOptions.ts
- src/fe/cli/index.ts
So that they can control the lifecycle of the guidebook's subprocesses
> feat: allow CLI callers to specify no-clean

- src/exec/options.ts
- src/exec/shell.ts
- src/fe/MadWizardOptions.ts
- src/fe/cli/defaults.ts
- src/index.ts
- src/profiles/index.ts
1) guidebooks can now use GUIDEBOOK_GLOBAL_DATA_PATH and GUIDEBOOK_PROFILE_DATA_PATH to store data that is either not specific to a profile, or specific to a profile, respectively.
2) madwizard now exports these and the full profile api via `import { Profiles } from 'madwizard'`
> feat: improve Profiles api, including GUIDEBOOK_PROFILE_DATA_PATH env var

- src/fe/cli/defaults.ts
- src/fe/cli/index.ts
This PR also cleans up the handling of command line options, so that defaults apply correctly when the user hasn't specified an option on the command line
> feat: restore interactive as the default guide mode

- src/fe/cli/index.ts
This will allow calling clients to consume environment variables that the guidebook produces.
> feat: guide should return the env map that the guidebook created

- src/memoization/index.ts
It currently types as `{}` rather than `typeof process.env`
> fix: bad typing on Memoizer.env

- src/profiles/clone.ts
- src/profiles/rename.ts
It was only changing the name of the profile file in the filesystem.
> fix: rename API is not changing the `name` field in the model itself

- src/profiles/index.ts
- src/profiles/persist.ts
e.g. resulting from a use of `write-file-atomic`
> feat: add Profiles.isTemporary() API to allow clients to know which profiles are temps

- src/choices/groups/index.ts
- src/fe/cli/index.ts
- src/parser/markdown/snippets/mirror.ts
This is an optimization, where we pre-generate the `blocks` model, and persist it along with the mirror. We do this to work around the extremely slow parsing from the `micromark` markdown parsing node module family.
For a 1.2MB source markdown, this reduces startup time from 7-8 seconds down to nearly 1 second. Node profiling shows that at least 30% of this slowness is due to micromark's array splicing. Oof, we're not going to fix that easily, hence this work.
ref: https://github.com/micromark/micromark/discussions/115
> feat: support for parsing source into ast at `mirror` time

- src/fe/cli/index.ts
- src/parser/markdown/snippets/mirror-paths.ts
- src/parser/markdown/snippets/mirror.ts
we don't need to load all of the markdown parsing logic when using a precompiled ast
> fix: optimize load time by deferring import of parsing logic

- src/fe/cli/index.ts
This is due to a regression in the dynamic import of the debug npm
> fix: debug: tasks fail

- src/profiles/paths.ts
I don't see any reason why we shouldn't always create the profiles directory.
> fix: change default mkdir option for profilesPath API to true

- src/profiles/list.ts
Instead, it will now return `[]`, i.e. an empty list of profiles.
> fix: `Profiles.list()` API should not fail if profiles directory does not exist

- src/fe/cli/index.ts
We aren't deregistering our `process.on("exit", ...)` handlers.
> fix: when run as part of a parent process, cleanup messages show up even after completion

- src/fe/MadWizardOptions.ts
- src/fe/cli/index.ts
- src/fe/guide/index.ts
this helps clients, which may be running multiple guidebooks concurrently, distinguish the output a bit better.
Either pass this into the CLI with a `{ name }` option, or via `$GUIDEBOOK_NAME`
> feat: allow clients to pass in a `name` option, and use this in logging

- README.md
- bin/regen.sh
- src/exec/EarlyExit.ts
- src/exec/shell.ts
- src/fe/guide/index.ts
- test/inputs/33/in.md
- test/inputs/33/run.txt
- test/inputs/33/tree-noaprioris.txt
- test/inputs/33/tree-noopt.txt
- test/inputs/33/tree.txt
- test/inputs/33/wizard-noaprioris.json
- test/inputs/33/wizard-noopt.json
- test/inputs/33/wizard.json
They do so by exiting with code `90`:
```shell
echo "stopping here"
exit 90
```
See tests/input/33/in.md, and the README.md for more info.
re: 90, 
> The author of this document proposes restricting user-defined exit codes to the range 64 - 113 (in addition to 0, for success), to conform with the C/C++ standard
ref: https://tldp.org/LDP/abs/html/exitcodes.html
> feat: allow code blocks to request an early, but normal, termination of the guidebook

- src/exec/ray-submit.ts
This will mess with program visibility in the ray workers.
> fix: in ray-submit, don't pass through a PATH env var

- src/exec/ray-submit.ts
we had `==` rather than `===`, and weren't stripping that option off from what we pass to the real `ray job submit`
> fix: minor fixes for ray-submit --no-input

- .npmignore
BREAKING CHANGE: any consumers that want the store will now need to install `@guidebooks/store` themselves. They can then version the store on their own.
> fix: stop publishing the guidebook store to npm

- .github/workflows/test.yml
- bin/regen.sh
- src/exec/shell.ts
- test/inputs/34/in.md
- test/inputs/34/run.txt
- test/inputs/34/tree-noaprioris.txt
- test/inputs/34/tree-noopt.txt
- test/inputs/34/tree.txt
- test/inputs/34/wizard-noaprioris.json
- test/inputs/34/wizard-noopt.json
- test/inputs/34/wizard.json
zsh by default does not perform word splitting when it expands unquoted shell variables. as a result
```shell
export FOO='--namespace bar'
```
```shell
kubectl get pods ${FOO}
```
would result in an "unknown option '--namespace bar'" from kubectl.
This PR adds zsh to the test matrix.
> fix: broken variable expansions for users with zsh as their shell

- src/exec/shell.ts
This should avoid a bash.exe window popup on Windows.
> fix: use `windowsHide: true` for subprocess execution

- src/fe/MadWizardOptions.ts
- src/fe/guide/index.ts
This PR adds this option, which allows for a run that only asks the user questions in the given guidebook.
> feat: new `--ifor` option (interactive only for a given guidebook)

- src/exec/ray-submit.ts
Ray is a bit particular here. If we pass through a RAY_ADDRESS with an http:// prefix, one may see this:
https://github.com/ray-project/ray/issues/21592
> AssertionError: Module: http does not have ClientBuilder
> fix: make sure to redact RAY_ADDRESS env var

- bin/regen.sh
- package.json
- src/choices/groups/expansion.ts
- test/inputs/41/in.md
- test/inputs/41/run-noaprioris.txt
- test/inputs/41/run-noopt.txt
- test/inputs/41/run.txt
- test/inputs/41/tree-noaprioris.txt
- test/inputs/41/tree-noopt.txt
- test/inputs/41/tree.txt
- test/inputs/41/wizard-noaprioris.json
- test/inputs/41/wizard-noopt.json
- test/inputs/41/wizard.json
If a tab expansion has the form:
```markdown
=== "expand(expr, message, key)"
```
i.e. it specifies the third argument `key`, then `key` will be interpreted as the name of an environment variable. If that environment variable has a value, then this value will be used not only as the result of the expansion, but also will be forced through as the desired choice.
This feature allows one guidebook to control another. For example, guidebook A may initialize some cluster resources. Later, guidebook B will want to clean up those resources. The names to be cleaned up should match, but guidebook B may also want to be general-purpose to allow any specified (i.e. via  choice) resource to be cleaned up.
See tests/input/41/in.md for an example.
> feat: allow guidebooks to specify a choice via env var

- src/fe/cli/madwizardRead.ts
- src/parser/markdown/snippets/index.ts
e.g. this load order:
- ml/codeflare (store-absolute) -> ./foo which resolves to ./foo/index.md and thus ml/codeflare/foo/index.md -> ./bar which should resolve to ./foo/bar.md and thus ml/codeflare/foo/bar.md
that last one is broken, i.e. a chained relative reference off an implicit index.md
> fix: relative imports chained off an implicit .../index file are broken

- bin/regen.sh
- src/parser/markdown/rehype-code-indexer/index.ts
- src/parser/markdown/util/isElement.ts
- src/parser/markdown/util/toMarkdownString.ts
- test/inputs/19/wizard-noaprioris.json
- test/inputs/19/wizard-noopt.json
- test/inputs/23/wizard-darwin.json
- test/inputs/23/wizard-linux.json
- test/inputs/23/wizard-noaprioris.json
- test/inputs/23/wizard-noopt.json
- test/inputs/23/wizard-win32.json
- test/inputs/42/assert.txt
- test/inputs/42/in.md
- test/inputs/42/run-noaprioris.txt
- test/inputs/42/run-noopt.txt
- test/inputs/42/run.txt
- test/inputs/42/tree-noaprioris.txt
- test/inputs/42/tree-noopt.txt
- test/inputs/42/tree.txt
- test/inputs/42/wizard-noaprioris.json
- test/inputs/42/wizard-noopt.json
- test/inputs/42/wizard.json
Descriptions that contain links or boldface, or any other non-plain text were being cropped so as only to show the content up to that non-plain content. Though this was only the case for descriptions occuring immediately after the choice marker, without an extra newline.
Was working properly:
```
=== "Choice"
Description **with bold** and trailing text
```
Was not working (madwizard only showed "Description", i.e. the text up to the bold part), and now fixed by this PR:
```
=== "Choice"
Description **with bold** and trailing text
```
See tests/inputs/42/in.md for an example.
> fix: choice descriptions with non-plain text may be cropped

- package-lock.json
- packages/madwizard-cli/package.json
now that we are using esbuild to build a single-file madwizard-cli bundle...
> chore: madwizard-cli only needs a devdep on madwizard

- package-lock.json
- packages/madwizard-cli/bin/madwizard
- packages/madwizard-cli/madwizard.js
- packages/madwizard-cli/package.json
to avoid a circular dependence of store on madwizard-cli
> fix: madwizard-cli should have a devdep on @guidebooks/store

- package-lock.json
- package.json
- packages/madwizard-cli/package.json
move it to the top-level package.json
> fix: madwizard-cli should not have a postinstall script

- package-lock.json
- packages/madwizard/src/fe/guide/index.ts
This pulls in a fix in `enquirer` that uses `strip-ansi` rather than `ansi-colors.unstyle` to strip off ansi control characters. What was happening: the latter does not understand how to strip off the terminal link/anchor ansi extension. The former does. Choice messages that contain terminal links would cause this problem to surface: up arrowing/down arrow would cause funky scrolling of the choice list.
https://github.com/enquirer/enquirer/pull/413
> fix: improved fix for up/down arrow sometimes causing funky scrolling

- packages/madwizard/src/fe/MadWizardOptions.ts
- packages/madwizard/src/fe/cli/commands/guide/handler.ts
- packages/madwizard/src/fe/cli/commands/plan/handler.ts
- packages/madwizard/src/fe/cli/commands/util.ts
- packages/madwizard/src/fe/cli/index.ts
- packages/madwizard/src/fe/cli/madwizardRead.ts
- packages/madwizard/src/parser/index.ts
- packages/madwizard/src/parser/markdown/index.ts
- packages/madwizard/src/test/index.ts
- packages/madwizard/src/test/programmatic-inputs.ts
```shell
cat foo.md | madwizard -
```
or, programmatically:
```
import { CLI } from 'madwizard'
CLI.cli(['madwizard', 'guide', '-'], undefined, { input })
```
In either case, the `-` part of the command line is necessary to indicate the desire not to treat the input as a file/uri.
> feat: support input from stdin and passed programmatically

- packages/madwizard/src/fe/MadWizardOptions.ts
- packages/madwizard/src/fe/cli/commands/guide/options.ts
- packages/madwizard/src/fe/cli/defaults.ts
- packages/madwizard/src/fe/guide/index.ts
- packages/madwizard/src/fe/raw/RawEvent.ts
- packages/madwizard/src/fe/raw/alldone.ts
- packages/madwizard/src/fe/raw/ask.ts
- packages/madwizard/src/fe/raw/index.ts
- packages/madwizard/src/fe/raw/qadone.ts
- packages/madwizard/src/fe/tree/ui.ts
Previously, the only option was to interact with the guide via stdin/stdout. Now, you can pass in a raw api handler `onRaw()` that allows for inversion of control (into a UI) via a programmatic interface.
```typescript
export type RawAskEvent = {
type: "ask"
ask: Prompt
onChoose(value: ValidAnswer): void
onCancel(): void
}
export type RawQADoneEvent = {
type: "qa-done"
}
export type RawAllDoneEvent = {
type: "all-done"
success: boolean
}
export type RawEvent = RawAskEvent | RawQADoneEvent | RawAllDoneEvent
```
> feat: allow clients to pass in a raw api callback function

- packages/madwizard/src/exec/handled-by-client.ts
- packages/madwizard/src/exec/index.ts
- packages/madwizard/src/fe/MadWizardOptions.ts
- packages/madwizard/src/fe/guide/index.ts
Pass a `shell` option:
```typescript
/**
* In case clients want to handle certain command line executions
* directly (rather than by shelling them out to a PTY).
*/
shell: {
willHandle(cmdline: string | boolean): boolean
exec(cmdline: string | boolean, env: import('../memoization/index.js').Memos['env']): Promise<"success">
}
```
> feat: allow clients to intercept shell executions

- packages/madwizard/src/fe/MadWizardOptions.ts
- packages/madwizard/src/parser/markdown/index.ts
- packages/madwizard/src/test/index.ts
- packages/madwizard/src/test/programmatic-inputs.ts
BREAKING CHANGE: this is to allow for specifying the filepath of the programmatic input.
> fix: switch programmatic input from `input: string` to `vfile: VFile`

- packages/madwizard/src/fe/cli/commands/guide/options.ts
we were telling yargs to set a default of true for commandLineOptions.interactive, which meant that the logic for interactive mode (in combining programmatic and command line options) was ignoring providedOptions
> fix: guide interactive mode detection is buggy

- package-lock.json
This is to avoid 2.3.6 conflicts from other deps. npm sometimes installs them in preference, even if those other deps are devdeps. I've never understood its proclivity to favor devdeps over deps.
> fix: bump to '2.3.7' of enquirier starpit fork

- packages/madwizard/src/fe/MadWizardOptions.ts
- packages/madwizard/src/fe/cli/commands/util.ts
- packages/madwizard/src/fe/cli/madwizardRead.ts
- packages/madwizard/src/fe/guide/EchoStream.ts
- packages/madwizard/src/fe/guide/index.ts
- packages/madwizard/src/fe/guide/taskrunner.ts
- packages/madwizard/src/profiles/paths.ts
- packages/madwizard/src/profiles/persist.ts
- packages/madwizard/src/profiles/restore.ts
This adds a `fs` field option to MadWizardOptions, that lets clients define shims for filesystem behavior. It also defers importing some of the non-browser-friendly bits (that aren't needed anyway, when in `raw` mode).
> feat: improved support for running in browser

- package-lock.json
- packages/madwizard/package.json
enquirer does not need the full power of readline; it appears to be using it (in lib/keypress.js) only to piggyback on the way readline hacks in a keypress event emitter.
NOTE: i had to hack in y18n and escalade into packages/madwizard/package.json. There seems to be a horrible (yes, another) bug in npm... yargs expresses a regular dependence on these two, but npm (both from 16.14 and 16.19) do not install either of these modules... at all, not anywhere.
> feat: switch enquirer from readline to keypress-browserify

- packages/madwizard/src/choices/groups/expansion.ts
- packages/madwizard/src/exec/Executor.ts
- packages/madwizard/src/exec/handled-by-client.ts
- packages/madwizard/src/fe/MadWizardOptions.ts
- packages/madwizard/src/graph/optimize.ts
- packages/madwizard/src/util/ora-delayed-promise.ts
BREAKING CHANGE: This removes untested and unused `exec` support in the Graph submodule.
> feat: support choice expansion via the client's `shell`

- packages/madwizard/src/exec/index.ts
Previously, we did not give the client an opportunity to handle the exec if the code block had an `exec` topmatter.
> fix: exec should trust client more broadly

- packages/madwizard/src/fe/cli/commands/guide/handler.ts
- packages/madwizard/src/fe/raw/ask.ts
- packages/madwizard/src/util/ora-delayed-promise.ts
when `ora` hides the cursor... it installs a SIGINT handler to clean up the hiding of the cursor. this causes major unreliability with ctrl+c handling.
```
// re: hideCursor: false, ugh, otherwise ctrl+c doesn't work reliably
// https://github.com/sindresorhus/ora/issues/27
// https://github.com/tapjs/signal-exit/issues/49
```
> fix: improved behavior w.r.t. ctrl+c cleanup

- packages/madwizard/src/fe/guide/index.ts
this PR fixes the "undefined" part. we will need to investigate why a ctrl+c results in a Run failed.
> fix: ctrl+c exit emits "Run failed: undefined"

- bin/madwizard
- package-lock.json
- packages/madwizard/src/fe/cli/commands/guide/handler.ts
- packages/madwizard/src/fe/guide/index.ts
- packages/madwizard/src/memoization/index.ts
wow, nodejs is a mess in this respect. enquirer isn't helping; it rejects with an empty string when a prompt is cancelled... we weren't handling that situation well.
This PR also removes the useless "please wait while we clean up" message when there's nothing to clean up
> fix: ctrl+c while enquirer prompt is active does not invoke cleanup handlers

- packages/madwizard-cli/test/run.sh
- packages/madwizard/src/parser/markdown/snippets/mirror-paths.ts
This also fixes the regression caused by #630 that was glossed over by this silent test failure bug.
> test: madwizard-cli test may silently fail

- packages/madwizard/src/exec/ray-submit.ts
- packages/madwizard/src/memoization/index.ts
BREAKING CHANGE: since this was part of the public Memos interface, this is a breaking change
> feat: remove now-unused `dependencies` field of `Memos`

- packages/madwizard/src/fe/MadWizardOptions.ts
- packages/madwizard/src/fe/cli/commands/profile/builder.ts
- packages/madwizard/src/fe/cli/commands/profile/import.ts
- packages/madwizard/src/profiles/exists.ts
This adds `-f/--force` and `-n/--name` options to `profile import`.
> fix: profile import should not by default overwrite an existing profile

- packages/madwizard/src/codeblock/CodeBlockProps.ts
- packages/madwizard/src/exec/custom.ts
- packages/madwizard/src/exec/index.ts
- packages/madwizard/src/exec/shell.ts
- packages/madwizard/src/fe/guide/index.ts
- packages/madwizard/src/parser/markdown/rehype-code-indexer/index.ts
This is dangerous, as e.g. putting one's laptop to sleep can send a signal to stdin, which can result in random subprocesses being suspended and never resuming. ctrl+z is another example.
This backs out https://github.com/guidebooks/madwizard/pull/694 which was a poor attempt at addressing this problem (that PR refused to process finally blocks on *any* signal)
With this change, you must now use `shell.stdin` to get a stdin attachment, as in:
```shell.stdin
while read line
do
echo "$line"
done < "${1:-/dev/stdin}"
```
> feat: do not attach stdin by default to code block execs

- packages/madwizard/src/exec/shell.ts
- packages/madwizard/src/fe/guide/index.ts
- packages/madwizard/src/memoization/index.ts
this also cleans up exec/shell a bit in a way that may help us in the future, by allowing callers of shellExec to consume the child process object directly
> fix: non-async subprocs are not killed!

- packages/madwizard/src/choices/groups/expansion.ts
kubernetes does not like uppercase letters in resource names
> fix: regression new shorter uuids were using uppercase letters
